# config.py
API_KEY = 'jcTIZOTsd1OsUOpgER'
API_SECRET = 'IlBRdxegRqhkWFyHWs2K9omWXTuCDyLEx7a6'
SECRET_1 = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
SECRET_2 = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6ODI4MzV9.ccZIwRRxe781qP0Mtlx62NIkmKyUGs155h433uxE-M0'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = [
"1CATUSDT", "1INCHUSDT", "A8USDT", "AAVEUSDT", "ACEUSDT", "ACHUSDT", "ADAUSDT", "AERGOUSDT", "AEROUSDT", "AEVOUSDT", "AGIUSDT", "AGLDUSDT", "AIOZUSDT", "AIUSDT", "AKROUSDT", "AKTUSDT", "ALEOUSDT", "ALGOUSDT", "ALICEUSDT", "ALPACAUSDT","ALPHAUSDT", "ALTUSDT", "AMBUSDT", "ANKRUSDT", 
"BADGERUSDT", "BAKEUSDT", "BALUSDT", "BANANAUSDT", "BANDUSDT", "BATUSDT", "BBUSDT", "BCHUSDT", "BEAMUSDT", "BELUSDT", "BENDOGUSDT", "BICOUSDT", "BIGTIMEUSDT", "BLASTUSDT", "BLURUSDT", "BLZUSDT", "BNBUSDT", "BNTUSDT", "BNXUSDT", "BOBAUSDT", "BOMEUSDT",
"BONDUSDT", "DARUSDT", "DASHUSDT", "DATAUSDT", "DEGENUSDT", "DENTUSDT", "DEXEUSDT", "DGBUSDT", "DODOUSDT", "DOGEUSDT", "DOGSUSDT", "DOGUSDT", "DOP1USDT", "DOTUSDT", "DRIFTUSDT", "DUSKUSDT", "DYDXUSDT", "DYMUSDT", 
"EDUUSDT", "EGLDUSDT", "ENAUSDT", "ENJUSDT", 
"HBARUSDT", "HFTUSDT", "HIFIUSDT", "HIGHUSDT", "HNTUSDT", "HOOKUSDT", "HOTUSDT", 
"ICPUSDT", "ICXUSDT", "IDEXUSDT", "IDUSDT", "ILVUSDT", "IMXUSDT", "INJUSDT", "IOSTUSDT", "IOTAUSDT", "IOTXUSDT", "IOUSDT", 
"JASMYUSDT", "JOEUSDT", "JSTUSDT", "JTOUSDT", 
"MAGICUSDT", "MANAUSDT", "MANEKIUSDT", "MANTAUSDT", "MASAUSDT", "MASKUSDT", "MAVIAUSDT", "MAVUSDT", "MAXUSDT", "MBLUSDT", "MBOXUSDT", "MDTUSDT", "MEMEUSDT", "MERLUSDT", "METISUSDT", "MEWUSDT", "MINAUSDT", "MKRUSDT", "MNTUSDT", "MOBILEUSDT", "MOCAUSDT", 
"PAXGUSDT", "PENDLEUSDT", "PENGUSDT", "PEOPLEUSDT", "PERPUSDT", "PHAUSDT", "PHBUSDT", "PIRATEUSDT", "PIXELUSDT", "PIXFIUSDT", "POLUSDT", "POLYXUSDT", "PONKEUSDT", "POPCATUSDT", "PORTALUSDT", "POWRUSDT", "PRCLUSDT", "PROMUSDT", "PYTHUSDT", "QIUSDT", "QNTUSDT", "QTUMUSDT",
"TAIKOUSDT", "TAOUSDT", "THETAUSDT", "TIAUSDT", "TLMUSDT", "TNSRUSDT", "TOKENUSDT", "TOMIUSDT", "TONUSDT", "TRBUSDT", "TRUUSDT", "TRXUSDT", "TUSDT", "TWTUSDT", "UMAUSDT", "UNFIUSDT", "UNIUSDT", "UXLINKUSDT", "VANRYUSDT", 
"APEUSDT", "API3USDT", "APTUSDT", "ARBUSDT", "ARKMUSDT", "ARKUSDT", "ARPAUSDT", "ARUSDT", "ASTRUSDT", "ATAUSDT", "ATHUSDT", "ATOMUSDT", "AUCTIONUSDT", "AUDIOUSDT", "AVAILUSDT", "AVAXUSDT", "AXLUSDT", "AXSUSDT", "ORDIUSDT", "ORNUSDT", "OSMOUSDT", "OXTUSDT"
]
  # Add your desired symbols
