# config.py
API_KEY = 'kumYhkreneOVab9rLM'
API_SECRET = 'PBz71EMCmFqTVuh6kdSJiDtkAwkOznmdUjxk'
SECRET_2 = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
SECRET_1 = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6ODI4MzV9.ccZIwRRxe781qP0Mtlx62NIkmKyUGs155h433uxE-M0'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
TELEGRAM_TOKEN = '7426543281:AAHu4Qf_KT6sGBaqUJU5ccFKZroHKrVc9R0'
CHAT_ID = '1385370555'
SELECTED_SYMBOLS = [
"1INCH/USDT", "1SOL/USDT", "3P/USDT", "5IRE/USDT", "A8/USDT", "AARK/USDT", "AAVE/USDT", "ACA/USDT", "ACH/USDT", "ACS/USDT", "ADA/USDT", "AEG/USDT", "AEVO/USDT", "AFC/USDT", "AFG/USDT", "AGI/USDT", "AGLA/USDT", "AGLD/USDT", "AIOZ/USDT", "AKI/USDT", "ALGO/USDT", "ALT/USDT", "ANKR/USDT", "APE/USDT", "APEX/USDT", "APP/USDT", "APRS/USDT", "APT/USDT", "APTR/USDT", "AR/USDT", "ARB/USDT", "ARKM/USDT", "ARTY/USDT", "ATH/USDT", "ATOM/USDT", "AURORA/USDT", "AURY/USDT", "AVA/USDT", "AVAIL/USDT", "AVAX/USDT", "AXL/USDT", "AXS/USDT", "AZY/USDT", 
"BABYDOGE/USDT", "BAT/USDT", "BB/USDT", "BBL/USDT", "BBSOL/USDT", "BCH/USDT", "BCUT/USDT", "BEAM/USDT", "BEL/USDT", "BICO/USDT", "BLAST/USDT", "BLOCK/USDT", "BLUR/USDT", "BNB/USDT", "BNT/USDT", "BOB/USDT", "BOBA/USDT", "BOME/USDT", "BONK/USDT", "BONUS/USDT", "BRAWL/USDT", "BRETT/USDT", "BTC/USDT", "BTC3L/USDT", "BTC3S/USDT", "BTG/USDT", "BTT/USDT", "BUBBLE/USDT", 
"C98/USDT", "CAKE/USDT", "CANDY/USDT", "CAPS/USDT", "CARV/USDT", "CAT/USDT", "CATI/USDT", "CATS/USDT", "CBK/USDT", "CBX/USDT", "CEL/USDT", "CELO/USDT", "CGPT/USDT", "CHRP/USDT", "CHZ/USDT", "CITY/USDT", "CLOUD/USDT", "CO/USDT", "COM/USDT", "COMP/USDT", "COOKIE/USDT", "COQ/USDT", "CORE/USDT", "COT/USDT", "CPOOL/USDT", "CRDS/USDT", "CRV/USDT", "CSPR/USDT", "CTA/USDT", "CTC/USDT", "CTT/USDT", "CYBER/USDT", 
"DAI/USDT", "DAPP/USDT", "DBR/USDT", "DCR/USDT", "DECHAT/USDT", "DEEP/USDT", "DEFI/USDT", "DEGEN/USDT", "DFI/USDT", "DGB/USDT", "DICE/USDT", "DLC/USDT", "DMAIL/USDT", "DOGE/USDT", "DOGS/USDT", "DOME/USDT", "DOP1/USDT", "DOT/USDT", "DPX/USDT", "DRIFT/USDT", "DSRUN/USDT", "DUEL/USDT", "DYDX/USDT", "DYM/USDT", "DZOO/USDT", 
"ECOX/USDT", "EGLD/USDT", "EGO/USDT", "EGP1/USDT", "EIGEN/USDT", "ELDA/USDT", "ELIX/USDT", "ENA/USDT", "ENJ/USDT", "ENS/USDT", "EOS/USDT", "ERTHA/USDT", "ESE/USDT", "ETC/USDT", "ETH/USDT", "ETH3L/USDT", "ETH3S/USDT", "ETHFI/USDT", "ETHW/USDT", "EVER/USDT", "EVERY/USDT", "EXVG/USDT", 
"FAME/USDT", "FAR/USDT", "FB/USDT", "FET/USDT", "FIDA/USDT", "FIL/USDT", "FIRE/USDT", "FITFI/USDT", "FLIP/USDT", "FLOKI/USDT", "FLOW/USDT", "FLR/USDT", "FLT/USDT", "FMB/USDT", "FMC/USDT", "FON/USDT", "FORT/USDT", "FOXY/USDT", "FTM/USDT", "FTT/USDT", "FXS/USDT", 
"G/USDT", "G3/USDT", "GALA/USDT", "GALAXIS/USDT", "GALFT/USDT", "GCAKE/USDT", "GENE/USDT", "GG/USDT", "GLMR/USDT", "GMRX/USDT", "GMT/USDT", "GMX/USDT", "GNS/USDT", "GODS/USDT", "GRAPE/USDT", "GRT/USDT", "GST/USDT", "GSTS/USDT", "GSWIFT/USDT", "GTAI/USDT", "GUMMY/USDT", 
"HBAR/USDT", "HERO/USDT", "HFT/USDT", "HLG/USDT", "HMSTR/USDT", "HNT/USDT", "HOOK/USDT", "HOT/USDT", "HTX/USDT", "HVH/USDT", 
"ICP/USDT", "ICX/USDT", "ID/USDT", "IMX/USDT", "INJ/USDT", "INSP/USDT", "INTER/USDT", "INTX/USDT", "IO/USDT", "IRL/USDT", "IZI/USDT", 
"JASMY/USDT", "JEFF/USDT", "JST/USDT", "JTO/USDT", "JUP/USDT", "JUV/USDT", 
"KARATE/USDT", "KAS/USDT", "KASTA/USDT", "KAVA/USDT", "KCAL/USDT", "KCS/USDT", "KDA/USDT", "KLAY/USDT", "KMNO/USDT", "KMON/USDT", "KOK/USDT", "KON/USDT", "KSM/USDT", 
"L3/USDT", "LADYS/USDT", "LAI/USDT", "LDO/USDT", "LENDS/USDT", "LEVER/USDT", "LFT/USDT", "LGX/USDT", "LINK/USDT", "LIS/USDT", "LL/USDT", "LMWR/USDT", "LOOKS/USDT", "LRC/USDT", "LTC/USDT", "LUNA/USDT", "LUNC/USDT", 
"MAGIC/USDT", "MAK/USDT", "MANA/USDT", "MANTA/USDT", "MASA/USDT", "MASK/USDT", "MAVIA/USDT", "MBOX/USDT", "MBS/USDT", "MBX/USDT", "MCG/USDT", "MCRT/USDT", "MDAO/USDT", "MEE/USDT", "MELOS/USDT", "MEME/USDT","MERL/USDT", "METH/USDT", "MEW/USDT", "MFER/USDT", "MINA/USDT", "MIX/USDT", "MKR/USDT", "MLK/USDT", "MNT/USDT", "MOCA/USDT", "MODE/USDT", "MOG/USDT", "MOJO/USDT", "MON/USDT","MOVR/USDT", "MPLX/USDT", "MSTAR/USDT", "MV/USDT", "MVL/USDT", "MX/USDT", "MXM/USDT", "MYRIA/USDT", "MYRO/USDT", 
"NAKA/USDT", "NAVX/USDT", "NEAR/USDT", "NEIRO/USDT", "NEON/USDT", "NESS/USDT", "NEXO/USDT", "NEXT/USDT", "NFT/USDT", "NGL/USDT", "NIBI/USDT", "NLK/USDT", "NOT/USDT", "NRN/USDT", "NUTS/USDT", "NYAN/USDT", "NYM/USDT", 
"OAS/USDT", "OBX/USDT", "OMG/USDT", "OMNI/USDT", "OMNICAT/USDT", "ONDO/USDT", "ONE/USDT", "OP/USDT", "ORDER/USDT", "ORDI/USDT", "ORT/USDT", 
"PARAM/USDT", "PAXG/USDT", "PBUX/USDT", "PENDLE/USDT", "PEOPLE/USDT", "PEPE/USDT", "PERP/USDT", "PIP/USDT", "PIRATE/USDT", "PIXFI/USDT", "PLANET/USDT", "PLT/USDT", "POKT/USDT", "POL/USDT", "PONKE/USDT", "POPCAT/USDT", "PORT3/USDT", "PORTAL/USDT", "PPT/USDT", "PRCL/USDT", "PRIMAL/USDT", "PRIME/USDT", "PSG/USDT", "PSP/USDT", "PSTAKE/USDT", "PTC/USDT", "PTU/USDT", "PUFF/USDT", "PUFFER/USDT", "PUMLX/USDT", "PURSE/USDT", "PYTH/USDT", 
"QMALL/USDT", "QNT/USDT", "QORPO/USDT", "QTUM/USDT", 
"RACA/USDT", "RAIN/USDT", "RATS/USDT", "RDNT/USDT", "REAL/USDT", "REN/USDT", "RENDER/USDT", "ROND/USDT", "ROOT/USDT", "ROSE/USDT", "RPK/USDT", "RPL/USDT", "RSS3/USDT", "RUBY/USDT", "RUNE/USDT", "RVN/USDT", 
"SAFE/USDT", "SAIL/USDT", "SALD/USDT", "SAND/USDT", "SAROS/USDT", "SATS/USDT", "SC/USDT", "SCA/USDT", "SCR/USDT", "SCRT/USDT", "SD/USDT", "SEI/USDT", "SEILOR/USDT","SEOR/USDT", "SFUND/USDT", "SHARK/USDT", "SHIB/USDT", "SHILL/USDT", "SHRAP/USDT", "SIDUS/USDT", "SIS/USDT", "SLP/USDT", "SNX/USDT", "SOCIAL/USDT", "SOL/USDT", "SOLO/USDT", "SON/USDT", "SPARTA/USDT", "SPEC/USDT", "SPELL/USDT", "SQD/USDT", "SQR/USDT", "SQT/USDT", "SRM/USDT", "SSV/USDT", "STAR/USDT", "STAT/USDT", "STETH/USDT", "STG/USDT", "STRK/USDT", "STRM/USDT", "STX/USDT", "SUI/USDT", 
"T/USDT", "TAI/USDT", "TAIKO/USDT", "TAP/USDT", "TAVA/USDT", "TEL/USDT", "TENET/USDT", "THETA/USDT", "THN/USDT", "TIA/USDT", "TIME/USDT", "TNSR/USDT", "TOKEN/USDT", "TOMI/USDT", "TON/USDT", "TRC/USDT", "TRVL/USDT", "TRX/USDT", "TST/USDT", "TURBOS/USDT", ", "TWT/USDT", 
"ULTI/USDT", "UMA/USDT", "UNI/USDT", "UXLINK/USDT", 
"VANRY/USDT", "VELA/USDT", "VELAR/USDT", "VELO/USDT", "VENOM/USDT", "VEXT/USDT", "VIC/USDT", "VINU/USDT", "VPAD/USDT", "VPR/USDT", "VRA/USDT", "VRTX/USDT", "VV/USDT" 
]

  # Add your desired symbols
