# config.py
API_KEY = 'kumYhkreneOVab9rLM'
API_SECRET = 'PBz71EMCmFqTVuh6kdSJiDtkAwkOznmdUjxk'
SECRET_2 = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
SECRET_1 = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6ODI4MzV9.ccZIwRRxe781qP0Mtlx62NIkmKyUGs155h433uxE-M0'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
TELEGRAM_TOKEN = '7426543281:AAHu4Qf_KT6sGBaqUJU5ccFKZroHKrVc9R0'
CHAT_ID = '1385370555'
SELECTED_SYMBOLS = [
"10000000AIDOGE/USDT", "1000000BABYDOGE/USDT", "1000000MOG/USDT", "1000000ΡΕΙPEI/USDT", "10000COQ/USDT", "10000LADYS/USDT", "10000SATS/USDT", "10000WEN/USDT", "10000WHY/USDT", "1000APU/USDT", "1000BONK/USDT", "1000BTT/USDT", "1000CATS/USDT", "1000CAT/USDT", "1000FLOKI/USDT", "1000LUNC/USDT", "1000MUMU/USDT", "1000NEIROCTO/USDT", "1000PEPE/USDT", "1000RATS/USDT", "1000TURBO/USDT", "1000XEC/USDT", "1000X/USDT", "1CAT/USDT", "1INCH/USDT", 
"A8/USDT", "AAVE/USDT", "ACE/USDT", "ACH/USDT", "ADA/USDT", "AERGO/USDT", "AERO/USDT", "AEVO/USDT", "AGI/USDT", "AGLD/USDT", "AIOZ/USDT", "AI/USDT", "AKRO/USDT", "AKT/USDT", "ALDO/USDT", "ALEO/USDT", "ALGO/USDT", "ALICE/USDT", "ALPACA/USDT", "ALPHA/USDT", "ALT/USDT", "AMB/USDT", "ANKR/USDT", "APE/USDT", "API3/USDT", "APT/USDT", "ARB/USDT", "ARKM/USDT", "ARK/USDT", "ARPA/USDT", "ATA/USDT", "ATH/USDT", "ATOM/USDT", "AUCTION/USDT", "AUDIO/USDT", "AVAIL/USDT", "AVAX/USDT", "AXL/USDT", "AXS/USDT", 
"BADGER/USDT", "BAKE/USDT", "BAL/USDT", "BANANA/USDT", "BAND/USDT", "BAT/USDT", "BB/USDT", "BCH/USDT", "BEAM/USDT", "BEL/USDT", "BENDOG/USDT", "BICO/USDT", "BIGTIME/USDT", "BLAST/USDT", "BLUR/USDT", "BLZ/USDT", "BNB/USDT", "BNT/USDT", "BNX/USDT", "BOBA/USDT", "BOME/USDT", "BOND/USDT", "BRETT/USDT", "BSV/USDT", "BSW/USDT", "BTC/USDT", 
"C98/USDT", "CAKE/USDT", "CARV/USDT", "CATI/USDT", "CCVX/USDT", "CELO/USDT", "CELR/USDT", "CETUS/USDT", "CFX/USDT", "CHESS/USDT", "CHR/USDT", "CHZ/USDT", "CKB/USDT", "CLOUD/USDT", "COMBO/USDT", "COMP/USDT", "CORE/USDT", "COS/USDT", "COTI/USDT", "CRO/USDT", "CRV/USDT", "CTC/USDT", "CTK/USDT", "CTSI/USDT", "CVC/USDT", "CYBER/USDT", 
"DAR/USDT", "DASH/USDT", "DATA/USDT", "DBR/USDT", "DEEP/USDT", "DEGEN/USDT", "DENT/USDT", "DEXE/USDT", "DGB/USDT", "DODO/USDT", "DOGE/USDT", "DOGS/USDT", "DOG/USDT", "DOP1/USDT", "DOT/USDT", "DRIFT/USDT", "DUSK/USDT", "DYDX/USDT", "DYM/USDT", 
"EDU/USDT", "EGLD/USDT", "EIGEN/USDT", "ENA/USDT", "ENJ/USDT", "ENS/USDT", "EOS/USDT", "ETC/USDT", "ETHFI/USDT", "ETH/USDT", "ETHW/USDT", 
"FB/USDT", "FDUSD/USDT", "FIDA/USDT", "FIL/USDT", "FIO/USDT", "FIRE/USDT", "FITFI/USDT", "FLM/USDT", "FLOW/USDT", "FLR/USDT", "FLUX/USDT", "FORTH/USDT", "FOXY/USDT", "FTM/USDT", "FTN/USDT", "FUN/USDT", "FXS/USDT", 
"GALA/USDT", "GAS/USDT", "GFT/USDT", "GLMR/USDT", "GLM/USDT", 	"GME/USDT", "GMT/USDT", "GMX/USDT", "GNO/USDT", "GOAT/USDT", "GODS/USDT", "GOMINING/USDT", "GRT/USDT", "GTC/USDT", "G/USDT", 
"HFT/USDT", "HHBAR/USDT", "HIFI/USDT", "HIGH/USDT", "HMSTR/USDT", "HNT/USDT", "HOOK/USDT", "HOT/USDT", "HPOS10I/USDT", 
"ICP/USDT", "ICX/USDT", "IDEX/USDT", "ID/USDT", "ILV/USDT", "INJ/USDT", "IOST/USDT", "IOTA/USDT", "IOTX/USDT", "IO/USDT", "JASMY/USDT", "JOE/USDT", "JST/USDT", "JTO/USDT", "JUP/USDT", 
"KAS/USDT", "KAVA/USDT", "KDA/USDT", "KEY/USDT", "KLAY/USDT", "KMNO/USDT", "KNC/USDT", "KSM/USDT", 
"L3/USDT", "LAI/USDT", "LEVER/USDT", "LINA/USDT", "LINK/USDT", "LISTA/USDT", "LIT/USDT", "LOOKS/USDT", "LPT/USDT", "LQTY/USDT", "LRC/USDT", "LSK/USDT", "LTC/USDT", "LTO/USDT", "LUMIA/USDT", "LUNA2/USDT", 
"MAGIC/USDT", "MANA/USDT", "MANEKI/USDT", "MANTA/USDT",	"MASA/USDT", "MASK/USDT", "MAVIA/USDT", "MAV/USDT", "MAX/USDT", "MBL/USDT", "MBOX/USDT", "MDT/USDT", "MEME/USDT", "MERL/USDT", "METIS/USDT", "MEW/USDT", "MINA/USDT", "MKR/USDT", "MNT/USDT", "MOBILE/USDT", "MOCA/USDT", "MON/USDT", "MOODENG/USDT", "MOTHER/USDT", "MOVR/USDT", "MTL/USDT", "MYRIA/USDT", "MYRO/USDT", 
"NEAR/USDT", "NEIROETH/USDT", "NEO/USDT", "NFP/USDT", "NKN/USDT", "NMR/USDT", "NOT/USDT", "NTRN/USDT", "NULS/USDT", "NYAN/USDT", 
"OGN/USDT", "OG/USDT", "OMG/USDT", "OMNI/USDT", "OM/USDT", "ONDO/USDT", "ONE/USDT", "ONG/USDT", "ONT/USDT", "OP/USDT", "ORBS/USDT", "ORCA/USDT", "ORDER/USDT", "ORDI/USDT", "OSMO/USDT", "OXT/USDT", 
"PAXG/USDT", "PENDLE/USDT", "PENG/USDT", "PEOPLE/USDT", "PERP/USDT", "PHA/USDT", "PHB/USDT", "PIRATE/USDT", "PIXEL/USDT", "PIXFI/USDT", "POL/USDT", "POLYX/USDT", "PONKE/USDT", "POPCAT/USDT", "PORTAL/USDT", "POWR/USDT", "PRCL/USDT", "PRIME/USDT", "PROM/USDT", "PUFFER/USDT", "PYR/USDT", "PYTH/USDT", 
"QI/USDT", "QNT/USDT", "QTUM/USDT", "QUICK/USDT", 
"RAD/USDT", "RARE/USDT", "RAYDIUM/USDT", "RDNT/USDT", "REEF/USDT", "RENDER/USDT", "REN/USDT", "REQ/USDT", "REZ/USDT", "RIF/USDT", "RLC/USDT", "RON/USDT", "ROSE/USDT", "RPL/USDT", "RSR/USDT", "RSS3/USDT", "RUNE/USDT", "RVN/USDT", 																				
"SAFE/USDT", "SAGA/USDT", "SAND/USDT", "SCA/USDT", "SCRT/USDT", "SCR/USDT", "SC/USDT", "SEI/USDT", "SFP/USDT", 	"SHIB1000/USDT", "SILLY/USDT", "SKL/USDT", "SLERF/USDT", "SLF/USDT", "SLP/USDT", "SNT/USDT", "SOL/USDT", "SPEC/USDT", "SPELL/USDT", "SNX/USDT", "SSV/USDT", "STEEM/USDT", "STG/USDT", "STMX/USDT", "STORJ/USDT", "STPT/USDT", "STRK/USDT", "STX/USDT", "SUI/USDT", "SUNDOG/USDT", "SUN/USDT", "SUPER/USDT", "SUSHI/USDT", "SWEAT/USDT", "SXP/USDT", "SYN/USDT", "SYS/USDT", 
"TAIKO/USDT", "TAO/USDT", "THETA/USDT", "TIA/USDT", "TLM/USDT", "TNSR/USDT", "TOKEN/USDT", "TOMI/USDT", "TON/USDT", "TRB/USDT", "TRU/USDT", "TRX/USDT", "T/USDT", "TWT/USDT",
"UMA/USDT", "UNFI/USDT", "UNI/USDT", "UXLINK/USDT", 
"VANRY/USDT", "VELO/USDT", "VET/USDT", "VIDT/USDT", "VOXEL/USDT", "VRA/USDT", "VTHO/USDT", 
"WAVES/USDT", "WAXP/USDT", "WIF/USDT", "WLD/USDT", "WOO/USDT", "W/USDT", 
"XAI/USDT", "XCH/USDT", "XCN/USDT", "XEM/USDT", "XIMX/USDT", "XLM/USDT", "XMR/USDT", "XNO/USDT", "XRD/USDT", "XRP/USDT", "XTZ/USDT", "XVG/USDT", "XVS/USDT", 
"YFI/USDT", "YGG/USDT", 
"ZBCN/USDT", "ZEC/USDT", "ZEN/USDT", "ZETA/USDT", "ZEUS/USDT", "ZIL/USDT", "ZKF/USDT", "ZKJ/USDT", "ZK/USDT", "ZRO/USDT", "ZRX/USDT"
]

