# config.py
API_KEY = 'kumYhkreneOVab9rLM'
API_SECRET = 'PBz71EMCmFqTVuh6kdSJiDtkAwkOznmdUjxk'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6ODI4MzV9.ccZIwRRxe781qP0Mtlx62NIkmKyUGs155h433uxE-M0'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = [
"ENSUSDT", "EOSUSDT", "ETCUSDT", "ETHBTCUSDT", "ETHFIUSDT", "ETHUSDT", "ETHWUSDT", "FDUSDUSDT", "FILUSDT", "FIREUSDT", "FITFIUSDT", "FLMUSDT", "FLOWUSDT", "FLRUSDT", "FLUXUSDT", "FORTHUSDT", "FOXYUSDT", "FTMUSDT", "ZECUSDT", "ZENUSDT", "ZETAUSDT", "ZEUSUSDT", 
"JUPUSDT", "KASUSDT", "KAVAUSDT", "KDAUSDT", "KEYUSDT", "KLAYUSDT", "KNCUSDT", "KSMUSDT", "L3USDT", "LAIUSDT", "LDOUSDT", "LEVERUSDT", "LINAUSDT", "LINKUSDT", "LISTAUSDT", "LITUSDT", "LOOKSUSDT", 
"MONUSDT", "MOTHERUSDT", "MOVRUSDT", "MTLUSDT", "MYRIAUSDT", "MYROUSDT", "NEARUSDT", "NEIROETHUSDT", "NEOUSDT", "NFPUSDT", "NKNUSDT", "NMRUSDT", "NOTUSDT", "NTRNUSDT", "NULSUSDT", "NYANUSDT", "OGNUSDT", "OGUSDT", 				
"QUICKUSDT", "RADUSDT", "MOVRUSDT", "RAYDIUMUSDT", "RDNTUSDT", "REEFUSDT", "RENDERUSDT", "RENUSDT", "REQUSDT", "REZUSDT", "RIFUSDT", "RLCUSDT", "RONUSDT", "ROSEUSDT", "RPLUSDT", "RSRUSDT", "RSS3USDT", "RUNEUSDT", 				
"VELOUSDT", "VETUSDT", "VIDTUSDT", "VOXELUSDT", "VRAUSDT", "VTHOUSDT", "WAVESUSDT", "WAXPUSDT", "WIFUSDT", "WLDUSDT", "WOOUSDT", "WUSDT", "XAIUSDT", "XCHUSDT", "XCNUSDT", "XEMUSDT", "XLMUSDT", 				
"COREUSDT", "COSUSDT", "COTIUSDT", "CROUSDT", "CRVUSDT", "CTCUSDT", "CTKUSDT", "CTSIUSDT", "CVCUSDT", "CVXUSDT", "CYBERUSDT", "SUSHIUSDT", "SWEATUSDT", "SXPUSDT", "SYNUSDT", "SYSUSDT", 						
"FTNUSDT", "FUNUSDT", "FXSUSDT", "GALAUSDT", "GASUSDT", "GFTUSDT", "GLMRUSDT", "GLMUSDT", "GMEUSDT", "GMTUSDT", "GMXUSDT", "ZILUSDT", "ZKFUSDT", "ZKJUSDT", "ZKUSDT", "ZROUSDT", "ZRXUSDT", 					
"LPTUSDT", "LQTYUSDT", "LRCUSDT", "LSKUSDT", "LTCUSDT", "LTOUSDT", "LUNA2USDT", "GNOUSDT", "GODSUSDT", "GRTUSDT", "GTCUSDT", "GUSDT", "STRKUSDT", "STXUSDT", "SUIUSDT", "SUNDOGUSDT", "SUNUSDT", "SUPERUSDT", 
"OMGUSDT", "OMNIUSDT", "OMUSDT", "ONDOUSDT", "ONEUSDT", "ONGUSDT", "ONTUSDT", "OPUSDT", "ORBSUSDT", "ORCAUSDT", "ORDERUSDT",
"RVNUSDT", "SAFEUSDT", "SAGAUSDT", "SANDUSDT", "SCAUSDT", "SCRTUSDT", "SCUSDT", "SEIUSDT", "SFPUSDT", "SHIB1000USDT", "SILLYUSDT",
"XMRUSDT", "XNOUSDT", "XRDUSDT", "XRPUSDT", "XTZUSDT", "XVGUSDT", "XVSUSDT", "YFIUSDT", "YGGUSDT", "ZBCNUSDT", 
"BRETTUSDT", "BSVUSDT", "BSWUSDT", "BTCUSDT", "C98USDT", "CAKEUSDT", "CELOUSDT", "CELRUSDT", "CETUSUSDT", "CFXUSDT", "CHESSUSDT", "CHRUSDT", "CHZUSDT", "CKBUSDT", "CLOUDUSDT", "COMBOUSDT", "COMPUSDT", "SKLUSDT", "SLERFUSDT", "SLFUSDT", "SLPUSDT", "SNTUSDT", "SNXUSDT", "SOLUSDT", "SPECUSDT", "SPELLUSDT", "SSVUSDT", "STEEMUSDT", "STGUSDT", "STMXUSDT", "STORJUSDT", "STPTUSDT"
]
