# config.py
API_KEY = 'kumYhkreneOVab9rLM'
API_SECRET = 'PBz71EMCmFqTVuh6kdSJiDtkAwkOznmdUjxk'
SECRET_2 = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
SECRET_1 = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
#TELEGRAM_TOKEN = '8066951467:AAHOaFDL9kixcdwtjbwb-szDgnl8R9Vz8AI'
TELEGRAM_TOKEN = '7291265041:AAHAsg1hnD1fe4eINhfd-86425ReI04lYJY'
CHAT_ID = '1385370555'
AVAILABLE_SYMBOLS = [
"10000000AIDOGEUSDT", "1000000BABYDOGEUSDT", "1000000MOGUSDT", "10000COQUSDT", "10000LADYSUSDT", "10000SATSUSDT", "10000WENUSDT", "10000WHYUSDT", "1000APUUSDT", "1000BONKUSDT", "1000BTTUSDT", "1000CATSUSDT", "1000CATUSDT", "1000FLOKIUSDT", "1000LUNCUSDT", "1000MUMUUSDT", "1000NEIROCTOUSDT", "1000PEPEUSDT", "1000RATSUSDT", "1000TURBOUSDT", "1000XECUSDT", "1000XUSDT", "1CATUSDT", "1INCHUSDT", 
"A8USDT", "AAVEUSDT", "ACEUSDT", "ACHUSDT", "ADAUSDT", "AERGOUSDT", "AEROUSDT", "AEVOUSDT", "AGIUSDT", "AGLDUSDT", "AIOZUSDT", "AIUSDT", "AKROUSDT", "AKTUSDT", "ALEOUSDT", "ALGOUSDT", "ALICEUSDT", "ALPACAUSDT", "ALPHAUSDT", "ALTUSDT", "AMBUSDT", "ANKRUSDT", "APEUSDT", "API3USDT", "APTUSDT", "ARBUSDT", "ARKMUSDT", "ARKUSDT", "ARPAUSDT", "ATAUSDT", "ATHUSDT", "ATOMUSDT", "AUCTIONUSDT", "AUDIOUSDT", "AVAILUSDT", "AVAXUSDT", "AXLUSDT", "AXSUSDT", 
"BADGERUSDT", "BAKEUSDT", "BALUSDT", "BANANAUSDT", "BANDUSDT", "BATUSDT", "BBUSDT", "BCHUSDT", "BEAMUSDT", "BELUSDT", "BENDOGUSDT", "BICOUSDT", "BIGTIMEUSDT", "BLASTUSDT", "BLURUSDT", "BLZUSDT", "BNBUSDT", "BNTUSDT", "BNXUSDT", "BOBAUSDT", "BOMEUSDT", "BONDUSDT", "BRETTUSDT", "BSVUSDT", "BSWUSDT", "BTCUSDT", 
"C98USDT", "CAKEUSDT", "CARVUSDT", "CATIUSDT", "CVXUSDT", "CELOUSDT", "CELRUSDT", "CETUSUSDT", "CFXUSDT", "CHESSUSDT", "CHRUSDT", "CHZUSDT", "CKBUSDT", "CLOUDUSDT", "COMBOUSDT", "COMPUSDT", "COREUSDT", "COSUSDT", "COTIUSDT", "CROUSDT", "CRVUSDT", "CTCUSDT", "CTKUSDT", "CTSIUSDT", "CVCUSDT", "CYBERUSDT", 
"DARUSDT", "DASHUSDT", "DATAUSDT", "DBRUSDT", "DEEPUSDT", "DEGENUSDT", "DENTUSDT", "DEXEUSDT", "DGBUSDT", "DODOUSDT", "DOGEUSDT", "DOGSUSDT", "DOGUSDT", "DOP1USDT", "DOTUSDT", "DRIFTUSDT", "DUSKUSDT", "DYDXUSDT", "DYMUSDT", 
"EDUUSDT", "EGLDUSDT", "EIGENUSDT", "ENAUSDT", "ENJUSDT", "ENSUSDT", "EOSUSDT", "ETCUSDT", "ETHFIUSDT", "ETHUSDT", "ETHWUSDT", 
"FBUSDT", "FDUSDUSDT", "FIDAUSDT", "FILUSDT", "FIOUSDT", "FIREUSDT", "FITFIUSDT", "FLMUSDT", "FLOWUSDT", "FLRUSDT", "FLUXUSDT", "FORTHUSDT", "FOXYUSDT", "FTMUSDT", "FTNUSDT", "FUNUSDT", "FXSUSDT", 
"GALAUSDT", "GASUSDT", "GFTUSDT", "GLMRUSDT", "GLMUSDT", "GMEUSDT", "GMTUSDT", "GMXUSDT", "GNOUSDT", "GOATUSDT", "GODSUSDT", "GOMININGUSDT", "GRTUSDT", "GTCUSDT", "GUSDT", 
"HFTUSDT", "HBARUSDT", "HIFIUSDT", "HIGHUSDT", "HMSTRUSDT", "HNTUSDT", "HOOKUSDT", "HOTUSDT", "HPOS10IUSDT", 
"ICPUSDT", "ICXUSDT", "IDEXUSDT", "IDUSDT", "ILVUSDT", "INJUSDT", "IOSTUSDT", "IOTAUSDT", "IOTXUSDT", "IOUSDT", "JASMYUSDT", "JOEUSDT", "JSTUSDT", "JTOUSDT", "JUPUSDT", 
"KASUSDT", "KAVAUSDT", "KDAUSDT", "KEYUSDT", "KLAYUSDT", "KMNOUSDT", "KNCUSDT", "KSMUSDT", 
"L3USDT", "LAIUSDT", "LEVERUSDT", "LINAUSDT", "LINKUSDT", "LISTAUSDT", "LITUSDT", "LOOKSUSDT", "LPTUSDT", "LQTYUSDT", "LRCUSDT", "LSKUSDT", "LTCUSDT", "LTOUSDT", "LUMIAUSDT", "LUNA2USDT", 
"MAGICUSDT", "MANAUSDT", "MANEKIUSDT", "MANTAUSDT", "MASAUSDT", "MASKUSDT", "MAVIAUSDT", "MAVUSDT", "MAXUSDT", "MBLUSDT", "MBOXUSDT", "MDTUSDT", "MEMEUSDT", "MERLUSDT", "METISUSDT", "MEWUSDT", "MINAUSDT", "MKRUSDT", "MNTUSDT", "MOBILEUSDT", "MOCAUSDT", "MONUSDT", "MOODENGUSDT", "MOTHERUSDT", "MOVRUSDT", "MTLUSDT", "MYRIAUSDT", "MYROUSDT", 
"NEARUSDT", "NEIROETHUSDT", "NEOUSDT", "NFPUSDT", "NKNUSDT", "NMRUSDT", "NOTUSDT", "NTRNUSDT", "NULSUSDT", "NYANUSDT", 
"OGNUSDT", "OGUSDT", "OMGUSDT", "OMNIUSDT", "OMUSDT", "ONDOUSDT", "ONEUSDT", "ONGUSDT", "ONTUSDT", "OPUSDT", "ORBSUSDT", "ORCAUSDT", "ORDERUSDT", "ORDIUSDT", "OSMOUSDT", "OXTUSDT", 
"PAXGUSDT", "PENDLEUSDT", "PENGUSDT", "PEOPLEUSDT", "PERPUSDT", "PHAUSDT", "PHBUSDT", "PIRATEUSDT", "PIXELUSDT", "PIXFIUSDT", "POLUSDT", "POLYXUSDT", "PONKEUSDT", "POPCATUSDT", "PORTALUSDT", "POWRUSDT", "PRCLUSDT", "PRIMEUSDT", "PROMUSDT", "PUFFERUSDT", "PYRUSDT", "PYTHUSDT", 
"QIUSDT", "QNTUSDT", "QTUMUSDT", "QUICKUSDT", 
"RADUSDT", "RAREUSDT", "RAYDIUMUSDT", "RDNTUSDT", "REEFUSDT", "RENDERUSDT", "RENUSDT", "REQUSDT", "REZUSDT", "RIFUSDT", "RLCUSDT", "RONUSDT", "ROSEUSDT", "RPLUSDT", "RSRUSDT", "RSS3USDT", "RUNEUSDT", "RVNUSDT", 																				
"SAFEUSDT", "SAGAUSDT", "SANDUSDT", "SCAUSDT", "SCRTUSDT", "SCRUSDT", "SCUSDT", "SEIUSDT", "SFPUSDT", "SHIB1000USDT", "SILLYUSDT", "SKLUSDT", "SLERFUSDT", "SLFUSDT", "SLPUSDT", "SNTUSDT", "SOLUSDT", "SPECUSDT", "SPELLUSDT", "SNXUSDT", "SSVUSDT", "STEEMUSDT", "STGUSDT", "STMXUSDT", "STORJUSDT", "STPTUSDT", "STRKUSDT", "STXUSDT", "SUIUSDT", "SUNDOGUSDT", "SUNUSDT", "SUPERUSDT", "SUSHIUSDT", "SWEATUSDT", "SXPUSDT", "SYNUSDT", "SYSUSDT", 
"TAIKOUSDT", "TAOUSDT", "THETAUSDT", "TIAUSDT", "TLMUSDT", "TNSRUSDT", "TOKENUSDT", "TOMIUSDT", "TONUSDT", "TRBUSDT", "TRUUSDT", "TRXUSDT", "TUSDT", "TWTUSDT",
"UMAUSDT", "UNFIUSDT", "UNIUSDT", "UXLINKUSDT", 
"VANRYUSDT", "VELOUSDT", "VETUSDT", "VIDTUSDT", "VOXELUSDT", "VRAUSDT", "VTHOUSDT", 
"WAVESUSDT", "WAXPUSDT", "WIFUSDT", "WLDUSDT", "WOOUSDT", "WUSDT", 
"XAIUSDT", "XCHUSDT", "XCNUSDT", "XEMUSDT", "XLMUSDT", "XMRUSDT", "XNOUSDT", "XRDUSDT", "XRPUSDT", "XTZUSDT", "XVGUSDT", "XVSUSDT", 
"YFIUSDT", "YGGUSDT", 
"ZBCNUSDT", "ZECUSDT", "ZENUSDT", "ZETAUSDT", "ZEUSUSDT", "ZILUSDT", "ZKFUSDT", "ZKJUSDT", "ZKUSDT", "ZROUSDT", "ZRXUSDT"
]
